/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * New data API of AviationWeather.gov. This supercedes the ADDS Data Server and AviationWeather Web Services.
 *
 * The version of the OpenAPI document: 3.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataCWA200Response
 */
export interface DataCWA200Response {
    /**
     * 
     * @type {object}
     * @memberof DataCWA200Response
     */
    data?: object;
}

/**
 * Check if a given object implements the DataCWA200Response interface.
 */
export function instanceOfDataCWA200Response(value: object): value is DataCWA200Response {
    return true;
}

export function DataCWA200ResponseFromJSON(json: any): DataCWA200Response {
    return DataCWA200ResponseFromJSONTyped(json, false);
}

export function DataCWA200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataCWA200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function DataCWA200ResponseToJSON(json: any): DataCWA200Response {
    return DataCWA200ResponseToJSONTyped(json, false);
}

export function DataCWA200ResponseToJSONTyped(value?: DataCWA200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

